version: "3.8"

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - productdb_volume:/data/db

  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1436:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password456?

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discountdb_volume:/var/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd123
      - POSTGRES_DB=discountdb

  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1435:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123?

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  # product.api:
  #   container_name: product.api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - RabbitMQUrl=rabbitmq
  #     - IdentityServerURL=http://identityserver.api
  #     - DatabaseSettings:ConnectionString=mongodb://productdb:27017
  #   ports:
  #     - "5011:80"
  #   depends_on:
  #     - productdb

  # identityserver.api:
  #   container_name: identityserver.api
  #   restart: on-failure
  #   ports:
  #     - "5001:80"
  #   depends_on:
  #     - identitydb
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings:default=Data Source=identitydb,1436;Initial Catalog=identityDb; User ID=sa; Password=Password456?;TrustServerCertificate=True;
